build: false
environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "pip install --upgrade pip"
install:
  - "cd sos-service"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
test_script:
  - "%PYTHON%/Scripts/nosetests"
