language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - "mvn package -f ./sos-compression/pom.xml"
  - "pip install --upgrade pip"

install:
  - "cd ./sos-service"
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - "nosetests --with-coverage"

after_success:
  - "coveralls --rcfile=./../.coveragerc"

notifications:
  email: false
